version: '3.8'
services:
  nestjs:
    image: node:latest
    container_name: nestjs_til
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
